Fix typos
python-cmd2/cmd2 pull request #1346
Opened 2024-10-23 19:14 UTC by kianmeng

Found via `codespell -L te,counterfit,afile` and `typos --hidden --format brief`

2024-10-23 19:22 UTC, tleonhardt requested changes

2024-10-23 19:22 UTC, tleonhardt commented on README.md
> -| [Expliot](https://gitlab.com/expliot_framework/expliot)         | Internet of Things (IoT) exploitation framework                                                                                 |
This is the name of the package and not a typo

2024-10-23 19:22 UTC, tleonhardt commented on readme_files/shout_out.csv
> +[Exploit](https://gitlab.com/expliot_framework/expliot),Internet of Things (IoT) exploitation framework
Same name of package not a typo

2024-10-23 19:22 UTC, tleonhardt commented on readme_files/shoutout.txt
> +Name: Microsoft/ Azure Counterfeit
Also name of a package

2024-10-23 19:29 UTC, kmvanbrunt requested changes
Thank you for this pull request. I appreciate you fixing our typos.
However, a few of the changes are incorrect. Please make the requested changes.

2024-10-23 19:29 UTC, kmvanbrunt commented on README.md
> +| [Exploit](https://gitlab.com/expliot_framework/expliot)         | Internet of Things (IoT) exploitation framework                                                                                 |
"Expliot" is the name of the software. It's not a typo.

2024-10-23 19:29 UTC, kmvanbrunt commented on readme_files/shout_out.csv
> +[Exploit](https://gitlab.com/expliot_framework/expliot),Internet of Things (IoT) exploitation framework
"Expliot" is the name of the software. It's not a typo.

2024-10-23 19:29 UTC, kmvanbrunt commented on readme_files/shoutout.txt
> +Name: Microsoft/ Azure Counterfeit
"Azure Counterfit" is the name of the software. It's not a typo.

2024-10-23 19:29 UTC, kmvanbrunt commented on readme_files/shoutout.txt
> +Description: Counterfeit is a command-line tool and generic automation layer for assessing the security of machine learning systems.
"Azure Counterfit" is the name of the software. It's not a typo.

2024-10-23 19:29 UTC, kmvanbrunt commented on tests/test_utils.py
> +    suggested_command = cu.suggest_similar("command", ["command", "UNRELATED", "NOT_SIMILAR"])
This unit test requires "command" to be misspelled. It's not a typo.

2024-10-23 19:29 UTC, kmvanbrunt commented on tests/test_utils.py
> +    suggested_command = cu.suggest_similar("command", ["UNRELATED", "NOT_SIMILAR"])
This unit test requires "command" to be misspelled. It's not a typo.

2024-10-23 19:29 UTC, kmvanbrunt commented on tests/test_utils.py
> +    suggested_command = cu.suggest_similar("command", [])
This unit test requires "command" to be misspelled. It's not a typo.

2024-10-23 20:20 UTC, tleonhardt commented
@kianmeng Thanks for this PR. We appreciate the typos you fixed. If you can address comments from the two of us to fix the things which actually are not typos, we would be happy to merge this in.  Thanks again!

2024-10-24 02:48 UTC, closed without merging

2024-10-24 02:48 UTC, kmvanbrunt commented
Closing since I'm doing this in another branch.

2024-10-24 13:29 UTC, kianmeng commented
@tleonhardt @kmvanbrunt Sorry guys, just saw your messages.